import citationSnapshot from "../../data/citations.json";
import rawProfile from "./profile.json";
import rawPublications from "./publications.json";

const EXPECTED_SCHOLAR_ID = "dcqk_mMAAAAJ";

interface CitationPaper {
  title: string;
  citations: number;
}

interface NormalizedCitationSnapshot {
  updatedAt: string;
  totalCitations: number;
  hIndex: number;
  i10Index: number;
  papers: CitationPaper[];
}

const normalizeTitle = (value: string) =>
  value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

const isNonNegativeInteger = (value: unknown): value is number =>
  Number.isInteger(value) && Number(value) >= 0;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const normalizePapers = (value: unknown): CitationPaper[] => {
  if (!Array.isArray(value)) return [];
  return value.flatMap((paper) => {
    if (!isRecord(paper) || typeof paper.title !== "string" || !isNonNegativeInteger(paper.citations)) return [];
    return [{ title: paper.title, citations: paper.citations }];
  });
};

const normalizeCitationSnapshot = (value: unknown): NormalizedCitationSnapshot | null => {
  if (!isRecord(value) || value.schemaVersion !== 1) return null;

  // CiteBeat's platform-neutral citation.snapshot/1 format.
  if (value.schema === "citation.snapshot") {
    if (!isRecord(value.source) || value.source.provider !== "scholar" || value.source.authorId !== EXPECTED_SCHOLAR_ID) return null;
    if (!isRecord(value.metrics)) return null;
    const papers = normalizePapers(value.papers);
    if (
      typeof value.source.fetchedAt !== "string" ||
      Number.isNaN(Date.parse(value.source.fetchedAt)) ||
      !isNonNegativeInteger(value.metrics.citations) ||
      !isNonNegativeInteger(value.metrics.hIndex) ||
      !isNonNegativeInteger(value.metrics.i10Index) ||
      papers.length === 0
    ) return null;
    return {
      updatedAt: value.source.fetchedAt,
      totalCitations: value.metrics.citations,
      hIndex: value.metrics.hIndex,
      i10Index: value.metrics.i10Index,
      papers,
    };
  }

  // Backward-compatible manual fallback generated by update-citations.mjs.
  const papers = normalizePapers(value.papers);
  if (
    value.source !== "Google Scholar" ||
    value.authorId !== EXPECTED_SCHOLAR_ID ||
    typeof value.updatedAt !== "string" ||
    Number.isNaN(Date.parse(value.updatedAt)) ||
    !isNonNegativeInteger(value.totalCitations) ||
    !isNonNegativeInteger(value.hIndex) ||
    !isNonNegativeInteger(value.i10Index) ||
    papers.length === 0
  ) return null;
  return {
    updatedAt: value.updatedAt,
    totalCitations: value.totalCitations,
    hIndex: value.hIndex,
    i10Index: value.i10Index,
    papers,
  };
};

const profile = structuredClone(rawProfile);
const publications = structuredClone(rawPublications);
const citations = normalizeCitationSnapshot(citationSnapshot);

if (citations) {
  const updatedAt = citations.updatedAt.slice(0, 10);
  const citationMetric = profile.metrics.find((metric) => metric.id === "citations");

  if (citationMetric) {
    citationMetric.value = String(citations.totalCitations);
    citationMetric.note.en = `h-index ${citations.hIndex} · i10-index ${citations.i10Index} · updated ${updatedAt}`;
    citationMetric.note.zh = `h-index ${citations.hIndex} · i10-index ${citations.i10Index} · 更新于 ${updatedAt}`;
  }

  const paperByTitle = new Map(
    citations.papers
      .map((paper) => [normalizeTitle(paper.title), paper]),
  );

  for (const publication of publications) {
    const paper = paperByTitle.get(normalizeTitle(publication.title));
    if (!paper) continue;
    publication.citations = {
      count: paper.citations,
      source: "Google Scholar",
      updatedAt,
    };
  }
}

export { profile, publications };
